name: terraform deploy
on: push

jobs:
  terraform-job:
   runs-on: 
   - self-hosted
   - JITU
  
   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.2
     
     - name: Azure Login
       uses: Azure/login@v3
       with:
        client-id: ${{ secrets.CLIENT }}
        tenant-id: ${{ secrets.TENANT }}
        subscription-id: ${{ secrets.SUBSCRIPTION }}
